### ISSUE TITLE
Veranstaltungsanmeldung

### ISSUE THREAD

**Issue by elliot2extreme** [majug/majug.github.io#3]
Für die Anmeldung einer Person zu einem Vortrag benötigen wir ein Google Formular, welches wir auf der Seite integrieren können.

Beispiel: [http://jug-da.de/termine/affen-testen/](http://jug-da.de/termine/affen-testen/)

**Comment by gtrefs** [comment]
Ich mach das mal zu. Wir haben jetzt ja Anmeldungen per Meetup: https://www.meetup.com/de-DE/mannheim-java-usergroup/
